### ISSUE TITLE
Add "-v" option to print the version string

### ISSUE THREAD

**Issue by kevinburkemeter** [remoteit/connectd#1]
Right now retrieving the version from a connectd binary is tricky, you have to print the entire help text and then try to parse it out. It would be nice if it shipped with "-v", "--version" or "version" arguments that would print the version string and then exit.

**Comment by danawoodman** [comment]
@kevinburkemeter thanks for the issue report, I've pinged @lowerpower who is the maintainer of connectd 👍

**Comment by lowerpower** [comment]
I will add to next release

**Comment by lowerpower** [comment]
fixed in 4.7 release
